name: river_warrior
description: Global Gamers Challenge 2024
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  add_to_google_wallet: ^0.0.3
  easy_localization: ^3.0.5
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/audio/
   - assets/images/
   - assets/images/backgrounds/
   - assets/images/items/
   - assets/images/others/
   - assets/images/powerups/
   - assets/translations/
  fonts:
    - family: Knewave
      fonts:
        - asset: assets/fonts/Knewave-Regular.ttf