name: river_warrior
description: Global Gamers Challenge
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  add_to_google_wallet: ^0.0.3
  flame: ^1.10.1
  flame_audio: ^2.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  uuid: ^4.3.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  lint: 

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/
   - assets/audio/
   - assets/images/
   - assets/images/backgrounds/
   - assets/images/items/
   - assets/images/others/
   - assets/images/powerups/
  fonts:
    - family: Knewave
      fonts:
        - asset: assets/fonts/Knewave-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#00000000"
  windows:
    generate: true
    image_path: "assets/favicon.png"
  macos:
    generate: true
    image_path: "assets/favicon.png"
    
flutter_native_splash:
  color: "#000000"
  image: "assets/favicon.png"
  android_screen_orientation: landscape

  android_12:
    color: "#000000"
    image: "assets/splash.png"